-- MySQL dump 10.13  Distrib 5.6.14, for osx10.7 (x86_64)
--
-- Host: localhost    Database: Configuration
-- ------------------------------------------------------
-- Server version	5.6.14

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `DataFormat`
--

DROP TABLE IF EXISTS `DataFormat`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DataFormat` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Surrogate Key identifier (autogenerated)',
  `Code` varchar(30) NOT NULL COMMENT 'Code identifying type of formats list',
  `Format` varchar(60) NOT NULL COMMENT 'Expected format of the data',
  `CreationTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ModificationTimestamp` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DataFormat_IDX1` (`Code`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `MappingDiscoveryRule`
--

DROP TABLE IF EXISTS `MappingDiscoveryRule`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `MappingDiscoveryRule` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Surogate Key identifier (autoincrement)',
  `CoreTable` varchar(64) NOT NULL COMMENT 'name of the target table from Core data model that given rule matches against',
  `CoreColumn` varchar(64) DEFAULT NULL COMMENT 'name of the target column that given rule matches against',
  `CoreType` varchar(30) DEFAULT NULL COMMENT 'whenever target Core Table containst role-driven records (of specific type) this defines an item that rule matches against. If CHOOSE value is present user will have a choice of type on mapping screen.',
  `RefCode` varchar(30) DEFAULT NULL COMMENT 'reference data table code that the data is matched against (see Configuration.ReferenceData.Code). If empty - no reference data check needed.',
  `RefFullScore` smallint(6) DEFAULT NULL COMMENT 'maximum score that matching operation can provide - it is guaranteed when matching percentage reaches value defined undedr "Ref Full Score % Threshold"',
  `RefMinimumPercMatch` decimal(3,2) DEFAULT NULL COMMENT 'minimum percentage of matches that has occur. Below this threshold score given by engine is 0. All matches above this threshold will give a score between 0 and "Ref Full Score" (prorated)',
  `RefFullScorePercThresh` decimal(3,2) DEFAULT NULL COMMENT 'reference data matching threshold after which the "Reff Full Score" is guaranteed. All below is proportionally calculated.',
  `NullMinimumPerc` decimal(3,2) DEFAULT NULL COMMENT 'minimum percentage of null values in source column',
  `NullMaximumPerc` decimal(3,2) DEFAULT NULL COMMENT 'maximum percentage of null values in source column',
  `NullPenalty` smallint(6) DEFAULT NULL COMMENT 'negative score (penalty) assigned when amount of nulls falls outside of range defined by "Null Min %" and "Null Max %"',
  `NamePatterns` varchar(256) DEFAULT NULL COMMENT 'list of comma separated patterns that name should meet to get "Name Score" points. Contains % that matches everything.',
  `NameScore` smallint(6) DEFAULT NULL COMMENT 'score given when source column name matches at least one of the names defined in "Name Patterns"',
  `MinimumValue` varchar(30) DEFAULT NULL COMMENT 'minimum allowed value',
  `MaximumValue` varchar(30) DEFAULT NULL COMMENT 'maximum allowed value',
  `AllowedExcPerc` decimal(3,2) DEFAULT NULL COMMENT 'percentage of exceptions allowed (data falling outside Min / Max Value range)',
  `ValScore` smallint(6) DEFAULT NULL COMMENT 'positive score given for the data meeting above value conditions',
  `ValPenalty` smallint(6) DEFAULT NULL COMMENT 'negative score (penalty) given for the data not meeting above value conditions',
  `FormatsCode` varchar(30) DEFAULT NULL COMMENT 'name of the code in Configuration.DataFormat.Code column that identifies allowed data formats',
  `FormatsMinimumPercThresh` decimal(3,2) DEFAULT NULL COMMENT 'minimum number of records (in percents) that has to meet formats table - otherwise the column is disqualified as a candidate',
  `FormatsMetScore` smallint(6) DEFAULT NULL COMMENT 'score given to column when correct formats threshold met',
  `MappingDiscoveryRulecol` varchar(45) DEFAULT NULL,
  `RegexPattern` varchar(256) DEFAULT NULL COMMENT 'regular expression checked against data',
  `RegexMinimumPercThresh` decimal(3,2) DEFAULT NULL COMMENT 'minumum number of records (in percents) that has to meet regex rule - otherwise the column is disqualified as a candidate',
  `RegexMetScore` smallint(6) DEFAULT NULL COMMENT 'score given to column when correct regex threshold met',
  `DataTypes` varchar(128) DEFAULT NULL COMMENT 'allowed source data types (if not met - column is rejected)',
  `MaybePointsThresh` smallint(6) NOT NULL COMMENT 'minimum number of points to be gathered to be considered as "Maybe" candidate',
  `ConfPointsThresh` smallint(6) NOT NULL COMMENT 'minimum number of points to be gathered to be considered as "Confident" candidate',
  `CreationTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ModificationTimestamp` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=94 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `ProfilingTemplate`
--

DROP TABLE IF EXISTS `ProfilingTemplate`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ProfilingTemplate` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Generated from sequence',
  `ExecutionLevel` varchar(10) NOT NULL COMMENT 'Defines what is the execution grain - COLUMN or TABLE',
  `TargetTableName` varchar(64) NOT NULL COMMENT 'Name of the target table',
  `Description` varchar(500) NOT NULL COMMENT 'Description of the template',
  `TemplateQuery` varchar(2000) NOT NULL COMMENT 'Template query, contains parameters (embraced with #)\n',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TargetTableName_UNIQUE` (`TargetTableName`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `ReferenceData`
--

DROP TABLE IF EXISTS `ReferenceData`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ReferenceData` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Surrogate Key identifier (autogenerated)',
  `Code` varchar(30) NOT NULL COMMENT 'Code identifying type of reference data dictionary',
  `Value` varchar(120) NOT NULL COMMENT 'Reference Data value',
  `CreationTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ModificationTimestamp` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ReferenceData_IDX1` (`Code`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `TokenAction`
--

DROP TABLE IF EXISTS `TokenAction`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `TokenAction` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Token` varchar(255) DEFAULT NULL,
  `UserID` int(11) NOT NULL,
  `Type` varchar(2) DEFAULT NULL,
  `CreationTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Expires` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Token_UNIQUE` (`Token`),
  KEY `fk_TokenAction_User1_idx` (`UserID`),
  CONSTRAINT `fk_TokenAction_User1` FOREIGN KEY (`UserID`) REFERENCES `User` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `User`
--

DROP TABLE IF EXISTS `User`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `User` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Generated from sequence',
  `CompanyName` varchar(60) NOT NULL COMMENT 'Company name',
  `ContactName` varchar(60) NOT NULL COMMENT 'Contact person name',
  `ContactPhone` varchar(20) DEFAULT NULL COMMENT 'Contact person phone number',
  `ContactEmail` varchar(200) NOT NULL COMMENT 'Contact person email address',
  `AddressLine1` varchar(120) DEFAULT NULL COMMENT 'Company address line 1',
  `AddressLine2` varchar(120) DEFAULT NULL COMMENT 'Company address line 2',
  `AddressLine3` varchar(120) DEFAULT NULL COMMENT 'Company address line 3',
  `Suburb` varchar(60) DEFAULT NULL COMMENT 'Company suburb',
  `State` varchar(30) DEFAULT NULL COMMENT 'Company state',
  `Postcode` int(11) DEFAULT NULL COMMENT 'Company postcode',
  `EncryptedPassword` varchar(60) NOT NULL COMMENT 'Encrypted password',
  `Active` tinyint(4) DEFAULT NULL COMMENT 'Account active',
  `EmailValidated` tinyint(4) DEFAULT NULL COMMENT 'Email validated',
  `LastLogin` timestamp NULL DEFAULT NULL COMMENT 'Last login',
  `CreationTimestamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ModificationTimestamp` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2014-01-08 23:49:05
